### PR TITLE
Add asset.description in map_asset

### PR DESCRIPTION
**Pull request by bricesanchez**
Please backport this feature in `middleman-v3-stable` branch

### CODE REVIEW

**Comment by dlitvakb** [comment]
Hey @bricesanchez,

This looks like a change we need to add!

Will, get into it as soon as I can

Cheers

**Comment by bricesanchez** [comment]
:+1: :)

**Comment by bricesanchez** [comment]
@dlitvakb I've fixed the specs to help you to merge this PR.

**Comment by dlitvakb** [comment]
Hey @bricesanchez,

Thank you very much for the PR Update!

Sorry it took so long to come around to it.

Merging

Cheers

**Pull request merged**
