### PR TITLE
Upgrade to CDA 2.0.1 & Add `_meta`

### LINKED ISSUE #93: Feature: Include created_at and updated_at in data files.
It would be nice to have the created_at and updated_at dates available for each record that gets created. Most of our records need to be sorted in some way, usually by date, and it's kind of a pain to have to keep creating additional fields on each content type for the publish date.

### LINKED ISSUE #103: Linked entries/assets not resolved on preview mode
**Edit 16.12.2016:** Apologies for the initial confusing title, I had a mixed up impression of what dynamic_entries do, the issue is the same but it has to do with linked entries/assets not being resolved, so please ignore what mention to dynamic_entries I make.

---

Hello there,

I'm using the `with_preview` method to preview a specific page that has linked assets and entries in some of its fields.

While the nonlinked fields are working correctly, the ones where an asset or another entry is referenced, are not being fetched, for example:

```
with_preview(space: 'CONTENTFUL_SPACE', access_token: 'CONTENTFUL_ACCESS_TOKEN' ) do |preview|
   @article = preview.entry('ENTRY_ID')
end

...

@article.inspect:

{
    ...
    [:post_category, "Article"],
    [:main_image, #"Link", :linkType=>"Asset", :id=>"C6y5BNKNYOUaUIIm2ccqU"}>] 
    ...
}
```

I've snooped into the gem's code a bit and I saw that [dynamic entries are set to :auto ](https://github.com/contentful/contentful_middleman/blob/3be8fdcf091cdf3d2b691c5ba18fc55a0a0ccb62/lib/contentful_middleman/tools/preview_proxy.rb#L54) so this should be getting all the linked stuff.

Is this the intended behaviour? If not I can make a recursive method to fetch all the stuff, but I wanted to check first before I do it.

Thanks again!

### LINKED ISSUE #113: Infinite loops via base mapper
The change made to `lib/contentful_middleman/mappers/base.rb` in 031fd8bf30649e98dd083bdf3a962a30555ba8d5 has introduced the possibility of infinite loops.

With the behaviour prior to the change, when an item that was previously `:discovered` was going to be mapped, it would only output the `id` of the item.

The change seems to have been implemented to ensure that subsequent references also output.

Unfortunately by always adding the item to the queue (regardless of if it has been discovered previously) it suddenly makes any cyclical references in Contentful trigger an infinite loop in the mapper, and it also seems to have left the `:discovered` logic orphaned (whereby `ids` are added to that array but never actually referenced by any useful logic, other than to check if other `ids` should be added to the array).

A best of both worlds approach would require an item being mapped to have an awareness of the `ids` of ancestors, so that it only gets mapped when the `id` does not exist in that ancestor chain (rather than simply being something that had been `:discovered` previously).

### LINKED ISSUE #116: Using `type` as the Field ID will result in no data being outputted for that Content Type when building the YAML files
I ran into this odd error while trying to figure out why a specific Content Type wasn't being returned anymore when running `middleman contentful`. The Content Type has 10 fields, and only the ID was being returned now. Very strange. I disabled each field one by one until I discovered that if it was a Short Text field that was causing this. More specifically, it was because I named the field ID `type`.  Once I changed the field ID to something like `itemType` it worked.

Why does this happen?

### LINKED ISSUE #117: How can we output the content type in entries? [Question]
We use `middleman_contentful` in our middleman app to pull down data from Contentful, and render it as Yaml. Works great. However, as we're trying to implement related entries across content types (aka sections or categories; so a blog entry referencing a podcast entry), it seems the `sys.id` property or `linkContentType` (in linked entries) isn't rendered in the yaml. We have no way of mapping these to our routes (folder slugs) in our app. We played around with include depth and it had no effect on that.

Is there a configuration setting in our middleman `config.rb` that would tell it to include the content type in entries (especially related entries)? This information seems kind of essential to making use of related entries at all. 

```
# Contentful configuration in config.rb
activate :contentful do |f|
    f.space = { site: '[hash]'}
    f.access_token = '[hash]'
    f.use_preview_api = false
    f.all_entries = true
    f.content_types = {
        blog: 'blog',
        podcastEntry: 'podcastEntry'
    }
end
```
Typical YAML blog entry, with related item, only outputs something like this:
```
:relatedEntries:
- :id: [hash]
  :title: 'podcast entry'
  :slug: podcast-name
```
And the JSON schema for the related entries looks like this:
```
...{
      "name": "Related Entries",
      "id": "relatedEntries",
      "type": "Array",
      "items": {
        "type": "Link",
        "linkType": "Entry",
        "validations": [
          {
            "linkContentType": [
              "blog",
              "podcastEntry"
            ]
          }
        ]
      }
```
Seems like it'd include `linkContentType` or something by default. If not, why? Is there a way we can have this returned & rendered into the Yaml files?

### PR DESCRIPTION
**Pull request by dlitvakb**
Fixes #116 
Fixes #113 
Fixes #103 
Fixes #117 
Fixes #93

### CODE REVIEW

**Comment by conraddecker** [comment]
Awesome, much needed...thanks @dlitvakb! Out of curiosity, will this find it's way into the experimental 4.0 branch any time soon? Or should I fork it and deal with it on my own?

**Comment by dlitvakb** [comment]
Hey @conraddecker, you can follow the discussion here and vote for your preferred approach: https://github.com/contentful/contentful_middleman/issues/56#issuecomment-292562322

Cheers

**Comment by conraddecker** [comment]
Sweet, thanks for the link and for all the hard work!

**Comment by dlitvakb** [comment]
Thanks! 😊

**Pull request merged**
